### ISSUE TITLE
Cisco C3850 stack missing data

### ISSUE THREAD

**Issue by bcoover** [tc45/GetInventory#6]
Run tool on C38xx stack and these fields were blank in spreadsheet:

- Model
- Serial number
- Uptime
- IOS Version
- IOS filename

Note that the inventory tab did have correct stuff

**Comment by bcoover** [comment]
Looks like from the error that this is because version returned a list object with two items, which could not be parsed. Need to add logic for stacks.

Error: 
ERROR - Show version failed due to error: Cannot convert ['FOC1950X0W5', 'FCW1950D0TS'] to Excel

**Comment by rubengm13** [comment]
Resolved in latest version.
